version: '2'
services:
  web:
    image: vilanovailageltru/decidim-vilanova:0.2.1
    restart: unless-stopped
    env_file: .env
    container_name: decidim_vilanova_web
    logging:
      driver: 'none'
    ports:
      - 80:80
    volumes:
      - /opt/decidim-vilanova/uploads:/home/app/decidim-vilanova/public/uploads
      - /opt/decidim-vilanova/log:/home/app/decidim-vilanova/log